export const countries = [
    { label: "Afghanistan", value: "AF", dialCode: "+93" },
    { label: "Albania", value: "AL", dialCode: "+355" },
    { label: "Algeria", value: "DZ", dialCode: "+213" },
    { label: "American Samoa", value: "AS", dialCode: "+1-684" },
    { label: "Andorra", value: "AD", dialCode: "+376" },
    { label: "Angola", value: "AO", dialCode: "+244" },
    { label: "Anguilla", value: "AI", dialCode: "+1-264" },
    { label: "Antarctica", value: "AQ", dialCode: "+672" },
    { label: "Antigua and Barbuda", value: "AG", dialCode: "+1-268" },
    { label: "Argentina", value: "AR", dialCode: "+54" },
    { label: "Armenia", value: "AM", dialCode: "+374" },
    { label: "Aruba", value: "AW", dialCode: "+297" },
    { label: "Australia", value: "AU", dialCode: "+61" },
    { label: "Austria", value: "AT", dialCode: "+43" },
    { label: "Azerbaijan", value: "AZ", dialCode: "+994" },
    { label: "Bahamas", value: "BS", dialCode: "+1-242" },
    { label: "Bahrain", value: "BH", dialCode: "+973" },
    { label: "Bangladesh", value: "BD", dialCode: "+880" },
    { label: "Barbados", value: "BB", dialCode: "+1-246" },
    { label: "Belarus", value: "BY", dialCode: "+375" },
    { label: "Belgium", value: "BE", dialCode: "+32" },
    { label: "Belize", value: "BZ", dialCode: "+501" },
    { label: "Benin", value: "BJ", dialCode: "+229" },
    { label: "Bermuda", value: "BM", dialCode: "+1-441" },
    { label: "Bhutan", value: "BT", dialCode: "+975" },
    { label: "Bolivia", value: "BO", dialCode: "+591" },
    { label: "Bosnia and Herzegovina", value: "BA", dialCode: "+387" },
    { label: "Botswana", value: "BW", dialCode: "+267" },
    { label: "Brazil", value: "BR", dialCode: "+55" },
    { label: "British Indian Ocean Territory", value: "IO", dialCode: "+246" },
    { label: "British Virgin Islands", value: "VG", dialCode: "+1-284" },
    { label: "Brunei", value: "BN", dialCode: "+673" },
    { label: "Bulgaria", value: "BG", dialCode: "+359" },
    { label: "Burkina Faso", value: "BF", dialCode: "+226" },
    { label: "Burundi", value: "BI", dialCode: "+257" },
    { label: "Cambodia", value: "KH", dialCode: "+855" },
    { label: "Cameroon", value: "CM", dialCode: "+237" },
    { label: "Canada", value: "CA", dialCode: "+1" },
    { label: "Cape Verde", value: "CV", dialCode: "+238" },
    { label: "Cayman Islands", value: "KY", dialCode: "+1-345" },
    { label: "Central African Republic", value: "CF", dialCode: "+236" },
    { label: "Chad", value: "TD", dialCode: "+235" },
    { label: "Chile", value: "CL", dialCode: "+56" },
    { label: "China", value: "CN", dialCode: "+86" },
    { label: "Christmas Island", value: "CX", dialCode: "+61" },
    { label: "Cocos Islands", value: "CC", dialCode: "+61" },
    { label: "Colombia", value: "CO", dialCode: "+57" },
    { label: "Comoros", value: "KM", dialCode: "+269" },
    { label: "Cook Islands", value: "CK", dialCode: "+682" },
    { label: "Costa Rica", value: "CR", dialCode: "+506" },
    { label: "Croatia", value: "HR", dialCode: "+385" },
    { label: "Cuba", value: "CU", dialCode: "+53" },
    { label: "Curacao", value: "CW", dialCode: "+599" },
    { label: "Cyprus", value: "CY", dialCode: "+357" },
    { label: "Czech Republic", value: "CZ", dialCode: "+420" },
    { label: "Democratic Republic of the Congo", value: "CD", dialCode: "+243" },
    { label: "Denmark", value: "DK", dialCode: "+45" },
    { label: "Djibouti", value: "DJ", dialCode: "+253" },
    { label: "Dominica", value: "DM", dialCode: "+1-767" },
    { label: "Dominican Republic", value: "DO", dialCode: "+1-809, 1-829, 1-849" },
    { label: "East Timor", value: "TL", dialCode: "+670" },
    { label: "Ecuador", value: "EC", dialCode: "+593" },
    { label: "Egypt", value: "EG", dialCode: "+20" },
    { label: "El Salvador", value: "SV", dialCode: "+503" },
    { label: "Equatorial Guinea", value: "GQ", dialCode: "+240" },
    { label: "Eritrea", value: "ER", dialCode: "+291" },
    { label: "Estonia", value: "EE", dialCode: "+372" },
    { label: "Ethiopia", value: "ET", dialCode: "+251" },
    { label: "Falkland Islands", value: "FK", dialCode: "+500" },
    { label: "Faroe Islands", value: "FO", dialCode: "+298" },
    { label: "Fiji", value: "FJ", dialCode: "+679" },
    { label: "Finland", value: "FI", dialCode: "+358" },
    { label: "France", value: "FR", dialCode: "+33" },
    { label: "French Polynesia", value: "PF", dialCode: "+689" },
    { label: "Gabon", value: "GA", dialCode: "+241" },
    { label: "Gambia", value: "GM", dialCode: "+220" },
    { label: "Georgia", value: "GE", dialCode: "+995" },
    { label: "Germany", value: "DE", dialCode: "+49" },
    { label: "Ghana", value: "GH", dialCode: "+233" },
    { label: "Gibraltar", value: "GI", dialCode: "+350" },
    { label: "Greece", value: "GR", dialCode: "+30" },
    { label: "Greenland", value: "GL", dialCode: "+299" },
    { label: "Grenada", value: "GD", dialCode: "+1-473" },
    { label: "Guam", value: "GU", dialCode: "+1-671" },
    { label: "Guatemala", value: "GT", dialCode: "+502" },
    { label: "Guernsey", value: "GG", dialCode: "+44-1481" },
    { label: "Guinea", value: "GN", dialCode: "+224" },
    { label: "Guinea-Bissau", value: "GW", dialCode: "+245" },
    { label: "Guyana", value: "GY", dialCode: "+592" },
    { label: "Haiti", value: "HT", dialCode: "+509" },
    { label: "Honduras", value: "HN", dialCode: "+504" },
    { label: "Hong Kong", value: "HK", dialCode: "+852" },
    { label: "Hungary", value: "HU", dialCode: "+36" },
    { label: "Iceland", value: "IS", dialCode: "+354" },
    { label: "India", value: "IN", dialCode: "+91" },
    { label: "Indonesia", value: "ID", dialCode: "+62" },
    { label: "Iran", value: "IR", dialCode: "+98" },
    { label: "Iraq", value: "IQ", dialCode: "+964" },
    { label: "Ireland", value: "IE", dialCode: "+353" },
    { label: "Isle of Man", value: "IM", dialCode: "+44-1624" },
    { label: "Israel", value: "IL", dialCode: "+972" },
    { label: "Italy", value: "IT", dialCode: "+39" },
    { label: "Ivory Coast", value: "CI", dialCode: "+225" },
    { label: "Jamaica", value: "JM", dialCode: "+1-876" },
    { label: "Japan", value: "JP", dialCode: "+81" },
    { label: "Jersey", value: "JE", dialCode: "+44-1534" },
    { label: "Jordan", value: "JO", dialCode: "+962" },
    { label: "Kazakhstan", value: "KZ", dialCode: "+7" },
    { label: "Kenya", value: "KE", dialCode: "+254" },
    { label: "Kiribati", value: "KI", dialCode: "+686" },
    { label: "Kosovo", value: "XK", dialCode: "+383" },
    { label: "Kuwait", value: "KW", dialCode: "+965" },
    { label: "Kyrgyzstan", value: "KG", dialCode: "+996" },
    { label: "Laos", value: "LA", dialCode: "+856" },
    { label: "Latvia", value: "LV", dialCode: "+371" },
    { label: "Lebanon", value: "LB", dialCode: "+961" },
    { label: "Lesotho", value: "LS", dialCode: "+266" },
    { label: "Liberia", value: "LR", dialCode: "+231" },
    { label: "Libya", value: "LY", dialCode: "+218" },
    { label: "Liechtenstein", value: "LI", dialCode: "+423" },
    { label: "Lithuania", value: "LT", dialCode: "+370" },
    { label: "Luxembourg", value: "LU", dialCode: "+352" },
    { label: "Macau", value: "MO", dialCode: "+853" },
    { label: "Macedonia", value: "MK", dialCode: "+389" },
    { label: "Madagascar", value: "MG", dialCode: "+261" },
    { label: "Malawi", value: "MW", dialCode: "+265" },
    { label: "Malaysia", value: "MY", dialCode: "+60" },
    { label: "Maldives", value: "MV", dialCode: "+960" },
    { label: "Mali", value: "ML", dialCode: "+223" },
    { label: "Malta", value: "MT", dialCode: "+356" },
    { label: "Marshall Islands", value: "MH", dialCode: "+692" },
    { label: "Mauritania", value: "MR", dialCode: "+222" },
    { label: "Mauritius", value: "MU", dialCode: "+230" },
    { label: "Mayotte", value: "YT", dialCode: "+262" },
    { label: "Mexico", value: "MX", dialCode: "+52" },
    { label: "Micronesia", value: "FM", dialCode: "+691" },
    { label: "Moldova", value: "MD", dialCode: "+373" },
    { label: "Monaco", value: "MC", dialCode: "+377" },
    { label: "Mongolia", value: "MN", dialCode: "+976" },
    { label: "Montenegro", value: "ME", dialCode: "+382" },
    { label: "Montserrat", value: "MS", dialCode: "+1-664" },
    { label: "Morocco", value: "MA", dialCode: "+212" },
    { label: "Mozambique", value: "MZ", dialCode: "+258" },
    { label: "Myanmar", value: "MM", dialCode: "+95" },
    { label: "Namibia", value: "NA", dialCode: "+264" },
    { label: "Nauru", value: "NR", dialCode: "+674" },
    { label: "Nepal", value: "NP", dialCode: "+977" },
    { label: "Netherlands", value: "NL", dialCode: "+31" },
    { label: "Netherlands Antilles", value: "AN", dialCode: "+599" },
    { label: "New Caledonia", value: "NC", dialCode: "+687" },
    { label: "New Zealand", value: "NZ", dialCode: "+64" },
    { label: "Nicaragua", value: "NI", dialCode: "+505" },
    { label: "Niger", value: "NE", dialCode: "+227" },
    { label: "Nigeria", value: "NG", dialCode: "+234" },
    { label: "Niue", value: "NU", dialCode: "+683" },
    { label: "North Korea", value: "KP", dialCode: "+850" },
    { label: "Northern Mariana Islands", value: "MP", dialCode: "+1-670" },
    { label: "Norway", value: "NO", dialCode: "+47" },
    { label: "Oman", value: "OM", dialCode: "+968" },
    { label: "Pakistan", value: "PK", dialCode: "+92" },
    { label: "Palau", value: "PW", dialCode: "+680" },
    { label: "Palestine", value: "PS", dialCode: "+970" },
    { label: "Panama", value: "PA", dialCode: "+507" },
    { label: "Papua New Guinea", value: "PG", dialCode: "+675" },
    { label: "Paraguay", value: "PY", dialCode: "+595" },
    { label: "Peru", value: "PE", dialCode: "+51" },
    { label: "Philippines", value: "PH", dialCode: "+63" },
    { label: "Pitcairn", value: "PN", dialCode: "+870" },
    { label: "Poland", value: "PL", dialCode: "+48" },
    { label: "Portugal", value: "PT", dialCode: "+351" },
    { label: "Puerto Rico", value: "PR", dialCode: "+1-787, 1-939" },
    { label: "Qatar", value: "QA", dialCode: "+974" },
    { label: "Republic of the Congo", value: "CG", dialCode: "+242" },
    { label: "Reunion", value: "RE", dialCode: "+262" },
    { label: "Romania", value: "RO", dialCode: "+40" },
    { label: "Russia", value: "RU", dialCode: "+7" },
    { label: "Rwanda", value: "RW", dialCode: "+250" },
    { label: "Saint Barthelemy", value: "BL", dialCode: "+590" },
    { label: "Saint Helena", value: "SH", dialCode: "+290" },
    { label: "Saint Kitts and Nevis", value: "KN", dialCode: "+1-869" },
    { label: "Saint Lucia", value: "LC", dialCode: "+1-758" },
    { label: "Saint Martin", value: "MF", dialCode: "+590" },
    { label: "Saint Pierre and Miquelon", value: "PM", dialCode: "+508" },
    { label: "Saint Vincent and the Grenadines", value: "VC", dialCode: "+1-784" },
    { label: "Samoa", value: "WS", dialCode: "+685" },
    { label: "San Marino", value: "SM", dialCode: "+378" },
    { label: "Sao Tome and Principe", value: "ST", dialCode: "+239" },
    { label: "Saudi Arabia", value: "SA", dialCode: "+966" },
    { label: "Senegal", value: "SN", dialCode: "+221" },
    { label: "Serbia", value: "RS", dialCode: "+381" },
    { label: "Seychelles", value: "SC", dialCode: "+248" },
    { label: "Sierra Leone", value: "SL", dialCode: "+232" },
    { label: "Singapore", value: "SG", dialCode: "+65" },
    { label: "Sint Maarten", value: "SX", dialCode: "+1-721" },
    { label: "Slovakia", value: "SK", dialCode: "+421" },
    { label: "Slovenia", value: "SI", dialCode: "+386" },
    { label: "Solomon Islands", value: "SB", dialCode: "+677" },
    { label: "Somalia", value: "SO", dialCode: "+252" },
    { label: "South Africa", value: "ZA", dialCode: "+27" },
    { label: "South Korea", value: "KR", dialCode: "+82" },
    { label: "South Sudan", value: "SS", dialCode: "+211" },
    { label: "Spain", value: "ES", dialCode: "+34" },
    { label: "Sri Lanka", value: "LK", dialCode: "+94" },
    { label: "Sudan", value: "SD", dialCode: "+249" },
    { label: "Suriname", value: "SR", dialCode: "+597" },
    { label: "Svalbard and Jan Mayen", value: "SJ", dialCode: "+47" },
    { label: "Swaziland", value: "SZ", dialCode: "+268" },
    { label: "Sweden", value: "SE", dialCode: "+46" },
    { label: "Switzerland", value: "CH", dialCode: "+41" },
    { label: "Syria", value: "SY", dialCode: "+963" },
    { label: "Taiwan", value: "TW", dialCode: "+886" },
    { label: "Tajikistan", value: "TJ", dialCode: "+992" },
    { label: "Tanzania", value: "TZ", dialCode: "+255" },
    { label: "Thailand", value: "TH", dialCode: "+66" },
    { label: "Togo", value: "TG", dialCode: "+228" },
    { label: "Tokelau", value: "TK", dialCode: "+690" },
    { label: "Tonga", value: "TO", dialCode: "+676" },
    { label: "Trinidad and Tobago", value: "TT", dialCode: "+1-868" },
    { label: "Tunisia", value: "TN", dialCode: "+216" },
    { label: "Turkey", value: "TR", dialCode: "+90" },
    { label: "Turkmenistan", value: "TM", dialCode: "+993" },
    { label: "Turks and Caicos Islands", value: "TC", dialCode: "+1-649" },
    { label: "Tuvalu", value: "TV", dialCode: "+688" },
    { label: "U.S. Virgin Islands", value: "VI", dialCode: "+1-340" },
    { label: "Uganda", value: "UG", dialCode: "+256" },
    { label: "Ukraine", value: "UA", dialCode: "+380" },
    { label: "United Arab Emirates", value: "AE", dialCode: "+971" },
    { label: "United Kingdom", value: "GB", dialCode: "+44" },
    { label: "United States", value: "US", dialCode: "+1" },
    { label: "Uruguay", value: "UY", dialCode: "+598" },
    { label: "Uzbekistan", value: "UZ", dialCode: "+998" },
    { label: "Vanuatu", value: "VU", dialCode: "+678" },
    { label: "Vatican", value: "VA", dialCode: "+379" },
    { label: "Venezuela", value: "VE", dialCode: "+58" },
    { label: "Vietnam", value: "VN", dialCode: "+84" },
    { label: "Wallis and Futuna", value: "WF", dialCode: "+681" },
    { label: "Western Sahara", value: "EH", dialCode: "+212" },
    { label: "Yemen", value: "YE", dialCode: "+967" },
    { label: "Zambia", value: "ZM", dialCode: "+260" },
    { label: "Zimbabwe", value: "ZW", dialCode: "+263" }
];
